### ISSUE TITLE
Inputting a non existent version into the URL leads to undefined package

### ISSUE THREAD

**Issue by boatbomber** [UpliftGames/wally#115]
It should default to the latest version instead.

Additionally related, dependencies use a range that may start at an invalid version but encompass valid versions, so clicking on the dependency can link to an invalid version.

**Comment by u-train** [comment]
2c:

> It should default to the latest version instead.

I think instead, it should take you to an error page with a link to the latest version, making it clear it isn't valid.

In the second case, it should default to a little dropdown showing all valid packages. If there's a lock file, it should highlight the one used by the lock file. Though, I don't think it's expected to upload a lock file with the package, so I don't see this being on the table.

**Comment by boatbomber** [comment]
Going to open a PR for this first issue in a minute. The dependency range one is going to be a bit more involved and will be a separate PR for reviewability.

![image](https://user-images.githubusercontent.com/40185666/224366250-1c7b7d61-5062-46a5-9bbe-f0696f79ab0b.png)
