### ISSUE TITLE
wally update issue - Mac OS 

### ISSUE THREAD

**Issue by matthewcawley-xdesign** [UpliftGames/wally#122]
I'm having an issue running `wally update`.

The following error is being returned:

```
❯ wally update
thread 'main' panicked at 'not yet implemented: The 'update' subcommand', src/commands/update.rs:9:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`wally install` runs fine.

Do you need any more information about my current setup?

**Comment by OverHash** [comment]
I think the error is pretty clear? `wally update` is currently not implemented.
