### ISSUE TITLE
Newlines in description hide package

### ISSUE THREAD

**Issue by ketrab2004** [UpliftGames/wally#123]
I added newlines into the description field of a package. Now it doesn't show up on the website.

When you search for it it doesn't show up at all. And when you go to the page directly it is just an empty white page. You only get these minified react errors in the console.
![image](https://user-images.githubusercontent.com/60228292/236825467-1c6f1645-56d2-4696-ab07-cbfb7af3bd46.png)

Lucikly downloading from the registry works fine.

Links:
[wally.toml](https://github.com/XolborGames/FuzzyString/blob/main/wally.toml)
[wally.run page](https://wally.run/package/xolborgames/fuzzy-string)
[wally-index](https://github.com/UpliftGames/wally-index/blob/main/xolborgames/fuzzy-string)

**Comment by ketrab2004** [comment]
I'm not 100% sure that this is because of the newlines, but [this package](https://wally.run/package/xolborgames/profileservice?version=1.0.0) works just fine and the only difference I see is the multiline description.

**Comment by MobiusCraftFlip** [comment]
Turns out the error was being caused by the incorrect sorting of package versions.

```typescript
const filteredPackageData = packageData.versions.some(
  (pack: WallyPackageMetadata) => !pack.package.version.includes("-")
)
  ? packageData.versions.filter(
      (pack: WallyPackageMetadata) => !pack.package.version.includes("-")
    )
  : packageData.versions
```
Someone forgot the final `.versions` :P
