### ISSUE TITLE
Package name in wally.toml doesn't match name in project.json

### ISSUE THREAD

**Issue by magnalite** [UpliftGames/wally#14]
Currently when we write packages to the Packages folder we write a script to be required along with the package. This script then finds the package in the _Index folder. It does this indexing based upon the name in the wally.toml. However when these folders are synced by rojo they get renamed to whatever is set in the project.json! This means the script we originally require can no longer find the package correctly!

As an example we can look at this Roact package

![image](https://user-images.githubusercontent.com/935417/128104952-542680cc-2a9a-4967-acb3-eb7ca0e949d0.png)
We can see it is `roblox_roact@1.4.0/Roact` as it has been renamed by rojo but the script we require will look for `roblox_roact@1.4.0/roact` as this is the name specified in the wally.toml. As a result we cannot require Roact.

**Comment by LPGhatguy** [comment]
We should fix this in the packages we've deployed so far, but I'm inclined to call this a Rojo bug. The name of the module should match the folder, not the `name` field in the package.
