### ISSUE TITLE
Wally produces flat file structure

### ISSUE THREAD

**Issue by LastTalon** [UpliftGames/wally#15]
For rodux and roact-rodux wally produces a flat file structure with backslashes in the names rather than the hierarchy it means to create. It creates the file structure normally for roact.

Happens with the linux release binary and when building from source on linux with v0.1.1.

![File Structure 1](https://i.imgur.com/84TE3I1.png) ![File Structure 2](https://i.imgur.com/FlJL1eh.png)

**Comment by LPGhatguy** [comment]
What the heck, that's a weird bug.

**Comment by magnalite** [comment]
It looks like the zip files themselves are broken like this! As opposed to this being an extraction issue on Linux. I think I accidentally broke all the packages when I republished them to change the project.json files. I assume that means this is an issue with zipping up packages on MacOS (and maybe linux).

**Comment by magnalite** [comment]
Looks like I messed up publishing somehow. I republished them again, use the exact same binary as last time, and they are fine now. Now sure how that happened but I don't think this is an issue we need to be immediately concerned with.

**Comment by magnalite** [comment]
This has occurred with another package uploaded via the wally cli. This seems to have happened to: `reselim/flipper@2.0.0`, `reselim/roact-flipper@1.1.0` and `reselim/roact-router@1.0.0`.

**Comment by magnalite** [comment]
It appears that unix -> windows is fine, windows -> windows is fine, but windows -> unix is flattened. (zipping -> unzipping)
