### ISSUE TITLE
Registry frontend should provide a searchable list of packages

### ISSUE THREAD

**Issue by grilme99** [UpliftGames/wally#18]
As Wally registries grow, it's going to become harder and harder to find the package you want and conveniently view its documentation. While you can use GitHub's "Go to file" feature to search a package by name in a specific registry, this doesn't give you an easy link to the packages GitHub repository or show you its README in a way NPM or Cargo would. Not only that but a website would allow you to easily view a packages version history, its dependencies and who depends on it, and who it was made by and other packages by them.

**Comment by magnalite** [comment]
0.3.0 now lets you search packages! Extra package data like you described is planned for future releases.
