### ISSUE TITLE
Configurable ignore paths for publishing

### ISSUE THREAD

**Issue by LPGhatguy** [UpliftGames/wally#22]
Many projects like Roact have Git submodules or other undesirable bits that we don't want to publish to the registry. We should allow users to configure what files are ignored in `wally.toml`.

**Comment by magnalite** [comment]
I think we should follow cargo's lead and have an include and an exclude field, copying the same behaviour, and each listing a set of gitignore patterns. I think we should also follow with respect to default behaviour ie: skip hidden files, if we are in a repo skip gitignore files and skip package folders which are generated by Wally.
