### ISSUE TITLE
Add a way to unpublish published packages

### ISSUE THREAD

**Issue by finobinos** [UpliftGames/wally#40]
Currently, there is no way to delete packages published to `https://github.com/UpliftGames/wally-index`. This is a problem as I can't  delete packages which are *accidentally* published...

Something like `wally unpublish` would do.

**Comment by magnalite** [comment]
As LastTalon said, we don't support removing packages. Instead you may only yank a package version. #3 Perhaps in the future we may support removing a package if it has never been downloaded but that isn't currently a planned feature.
