### ISSUE TITLE
Ability to add a @latest to the versioning at wally.toml

### ISSUE THREAD

**Issue by imacodr** [UpliftGames/wally#78]
Currently when starting a new project and well adding new dependencies you usually don't want to constantly leave to look at what versioning the package is at on wally.run, with that I would love to be able to pass a @latest versioning which follows semver and multiple other package managers use to easily get the latest version of that package.

**Comment by LastTalon** [comment]
I don't think this makes much sense to have `latest` in the manifest. It would be nice to see a command like `wally install` support the ability to automatically add the latest version of a dependency to the manifest at that version.

**Comment by magnalite** [comment]
Yeah I agree we could make adding a new package or updating a package version in a manifest smoother and https://github.com/UpliftGames/wally/issues/74 would be a good way to achieve this. We can safely assume that if a dependency is added without a version specified then we should add the latest version. This only makes sense at the command level though and we should always have versions specified within the manifest. 

We certainly don't want an `@latest` tag in the manifest though. It is misleading and easily becomes dangerous. We can already shift versions in a semver compliant way and to go further means we will break things.
