### ISSUE TITLE
Failure to compile Wally from source

### ISSUE THREAD

**Issue by GnomeDevs** [UpliftGames/wally#82]
Wally cloned into /home/[username]/wally
Ran ```cargo install --locked --path wally``` on /home/[username]/

It did not work and returned a ```failed to load source for dependency "rocket" error.```

System: Manjaro (Arch ARM64)

Also, if possible I would like to run the wally executable provided along with the linux.zip file, but it doesn't seem to function well.

**Comment by FxllenCode** [comment]
Make sure you are on rust nightly. iirc rocket requires nightly rust.

**Comment by LPGhatguy** [comment]
> Make sure you are on rust nightly. iirc rocket requires nightly rust.

Rocket's Git releases do not require nightly Rust. Are you trying to install the registry?

You might be able to run

```bash
cargo install --locked --path wally --package wally
```

to ensure that you're only building the CLI and not the backend.

**Comment by GnomeDevs** [comment]
Thanks, guys. Problem solved.
