### ISSUE TITLE
evaera\promise@4.0.0 wally package throws error "Access is denied. (os error 5)"

### ISSUE THREAD

**Issue by synthranger** [UpliftGames/wally#91]
### Without Promise in dependencies
<img src="https://user-images.githubusercontent.com/86300361/177029819-c9fcd225-23ac-4105-a81b-cfe6f3c913ea.png" width="75%"/>

### With Promise in dependencies
<img src="https://user-images.githubusercontent.com/86300361/177030302-ab52ca4c-17e0-410a-a639-9edba2abb624.png" width="75%"/>

### With Packages that has Promise as a dependency
<img src="https://user-images.githubusercontent.com/86300361/177030484-6e1724fe-b9d8-4905-a149-6ce085105eea.png" width="75%"/>

I have reported this already to the package's repo and evaera told me that it is not an issue on their end and suggested me to open an issue here instead. I really have no idea why this happens and have tried all sorts of ways to try and fix this issue like deleting the Packages folder in my repo and giving wally.exe administrator and yet it still throws this ambiguous error.

**Comment by Dekkonot** [comment]
Unable to reproduce (albeit two years later...). Re-open if it's still a problem.
