### ISSUE TITLE
How do you include packages for testing your project without including them in the release?

### ISSUE THREAD

**Issue by L3G5ND** [UpliftGames/wally#97]
I saw that all my packages included with Wally were included in the published release so I thought adding them to [dev-dependencies] would fix it, I was wrong. How would I accomplish this?

**Comment by magnalite** [comment]
If dev-dependencies is the _only_ source for the dependant then it should only place it in the DevDependencies folder. If dev-dependencies doesn't do that then that is a separate issue.
